# Generated by Django 4.0.6 on 2022-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_name_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
